services:
  api:
    build:
      context: .
      dockerfile: SkillSystem.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SkillSystem;User=sa;Password=1;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
